spring:
  kafka:
    bootstrap-servers: kafka:9092
  application:
    name: Service-B
  datasource:
    url: jdbc:mysql://localhost:3306/micro_service?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8082

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always