spring:
  application:
    name: Api-Gateway
  cloud:
    gateway:
      routes:
        - id: service-a-route
          uri: lb://SERVICE-A
          predicates:
            - Path=/service-a/**
          filters:
            - StripPrefix=1

        - id: service-b-route
          uri: lb://SERVICE-B
          predicates:
            - Path=/service-b/**
          filters:
            - StripPrefix=1

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always