spring:
  kafka:
    bootstrap-servers: kafka:9092
  application:
    name: Service-A
  datasource:
    url: jdbc:postgresql://postgres:5432/micro_service
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081


eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always