spring:
  application:
    name: Eureka-Server

server:
  port: 8761

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost
    prefer-ip-address: false